server:
  port: 8082

spring:
  application:
    name: activity-service

  config:
    import: optional:application.secret.yml


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka