server:
  port: 8081

spring:
  application:
    name: user-service

  config:
    import: optional:application.secret.yml

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
